import type { CommunityPost, Message, Place } from "../types";

export const mockPlaces: Place[] = [
  {
    id: "1",
    name: "The Velvet Nook",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7769,
    lng: 106.7009,
    category: "Cafe",
    rating: 4.8,
    image: "https://picsum.photos/seed/jazz/800/600",
    images: ["https://picsum.photos/seed/jazz/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$$$",
    description: "A cozy jazz cafe for quiet conversations.",
    openingHours: "18:00 - 23:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Evening",
      target: "Couples",
      outfit: "Smart casual",
    },
    source: "mock",
  },
  {
    id: "2",
    name: "Skyline Peaks",
    address: "Tan Binh District, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.8231,
    lng: 106.6297,
    category: "Outdoor",
    rating: 4.9,
    image: "https://picsum.photos/seed/hiking/800/600",
    images: ["https://picsum.photos/seed/hiking/800/600"],
    vibe: "Active & Outdoors",
    priceRange: "$",
    description: "An energetic outdoor spot with skyline views.",
    openingHours: "06:00 - 18:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Morning",
      target: "Active dates",
      outfit: "Comfortable",
    },
    source: "mock",
  },
  {
    id: "3",
    name: "Canvas & Clay",
    address: "District 3, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7827,
    lng: 106.6958,
    category: "Entertainment",
    rating: 4.7,
    image: "https://picsum.photos/seed/art/800/600",
    images: ["https://picsum.photos/seed/art/800/600"],
    vibe: "Culture & Arts",
    priceRange: "$$",
    description: "A creative pottery and art date experience.",
    openingHours: "09:00 - 21:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Afternoon",
      target: "Creative couples",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "4",
    name: "Neon Beats",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7736,
    lng: 106.7048,
    category: "Entertainment",
    rating: 4.5,
    image: "https://picsum.photos/seed/arcade/800/600",
    images: ["https://picsum.photos/seed/arcade/800/600"],
    vibe: "Social & Loud",
    priceRange: "$$",
    description: "An arcade-style date spot with games and music.",
    openingHours: "10:00 - 23:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Night",
      target: "Fun dates",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "5",
    name: "Secret Garden",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7795,
    lng: 106.7015,
    category: "Food",
    rating: 4.8,
    image: "https://picsum.photos/seed/garden/800/600",
    images: ["https://picsum.photos/seed/garden/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$$",
    description: "A garden-style restaurant for relaxed dinners.",
    openingHours: "11:00 - 22:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Dinner",
      target: "Romantic dates",
      outfit: "Smart casual",
    },
    source: "mock",
  },
  {
    id: "6",
    name: "Paddle & Picnic",
    address: "Binh Thanh District, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7961,
    lng: 106.7214,
    category: "Outdoor",
    rating: 4.6,
    image: "https://picsum.photos/seed/kayak/800/600",
    images: ["https://picsum.photos/seed/kayak/800/600"],
    vibe: "Active & Outdoors",
    priceRange: "$$",
    description: "A light outdoor date with picnic vibes.",
    openingHours: "07:00 - 18:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Morning",
      target: "Outdoor lovers",
      outfit: "Sporty casual",
    },
    source: "mock",
  },
  {
    id: "7",
    name: "The Opera House",
    address: "Ben Nghe, District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7766,
    lng: 106.7031,
    category: "Culture",
    rating: 4.9,
    image: "https://picsum.photos/seed/opera/800/600",
    images: ["https://picsum.photos/seed/opera/800/600"],
    vibe: "Culture & Arts",
    priceRange: "$$$$",
    description: "A classic cultural landmark for elegant dates.",
    openingHours: "Event dependent",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Evening",
      target: "Culture dates",
      outfit: "Elegant",
    },
    source: "mock",
  },
  {
    id: "8",
    name: "Bunker Bar",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7812,
    lng: 106.6985,
    category: "Food",
    rating: 4.4,
    image: "https://picsum.photos/seed/techno/800/600",
    images: ["https://picsum.photos/seed/techno/800/600"],
    vibe: "Social & Loud",
    priceRange: "$$$",
    description: "A lively food and drink spot for late-night plans.",
    openingHours: "18:00 - 01:00",
    reviews: [],
    reviewSentiment: "Mixed",
    recommendations: {
      bestTime: "Late night",
      target: "Social dates",
      outfit: "Trendy casual",
    },
    source: "mock",
  },
  {
    id: "9",
    name: "Whispering Woods",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7875,
    lng: 106.7052,
    category: "Outdoor",
    rating: 4.7,
    image: "https://picsum.photos/seed/botanical/800/600",
    images: ["https://picsum.photos/seed/botanical/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$",
    description: "A calm green space for slow walks.",
    openingHours: "06:00 - 19:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Morning",
      target: "Quiet dates",
      outfit: "Comfortable",
    },
    source: "mock",
  },
  {
    id: "10",
    name: "City Cycle",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7758,
    lng: 106.7011,
    category: "Outdoor",
    rating: 4.6,
    image: "https://picsum.photos/seed/cycle/800/600",
    images: ["https://picsum.photos/seed/cycle/800/600"],
    vibe: "Active & Outdoors",
    priceRange: "$$",
    description: "A casual cycling date idea around the city.",
    openingHours: "07:00 - 20:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Late afternoon",
      target: "Active dates",
      outfit: "Sporty",
    },
    source: "mock",
  },
  {
    id: "11",
    name: "Lumiere Cinema",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7781,
    lng: 106.6992,
    category: "Entertainment",
    rating: 4.8,
    image: "https://picsum.photos/seed/cinema/800/600",
    images: ["https://picsum.photos/seed/cinema/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$$",
    description: "A cozy cinema for simple date nights.",
    openingHours: "10:00 - 23:30",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Evening",
      target: "Movie dates",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "12",
    name: "Aroma Roastery",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7805,
    lng: 106.7035,
    category: "Cafe",
    rating: 4.7,
    image: "https://picsum.photos/seed/coffee/800/600",
    images: ["https://picsum.photos/seed/coffee/800/600"],
    vibe: "Culture & Arts",
    priceRange: "$$",
    description: "A modern roastery with a calm creative vibe.",
    openingHours: "07:00 - 22:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Afternoon",
      target: "Coffee dates",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "13",
    name: "Zenith Yoga",
    address: "District 3, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7842,
    lng: 106.7068,
    category: "Outdoor",
    rating: 4.9,
    image: "https://picsum.photos/seed/yoga/800/600",
    images: ["https://picsum.photos/seed/yoga/800/600"],
    vibe: "Active & Outdoors",
    priceRange: "$$",
    description: "A wellness-focused activity for mindful dates.",
    openingHours: "06:00 - 21:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Morning",
      target: "Wellness dates",
      outfit: "Activewear",
    },
    source: "mock",
  },
  {
    id: "14",
    name: "The Gilded Fork",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7725,
    lng: 106.7022,
    category: "Food",
    rating: 4.9,
    image: "https://picsum.photos/seed/fine-dining/800/600",
    images: ["https://picsum.photos/seed/fine-dining/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$$$$",
    description: "A fine dining option for special dates.",
    openingHours: "17:30 - 22:30",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Dinner",
      target: "Anniversary dates",
      outfit: "Elegant",
    },
    source: "mock",
  },
  {
    id: "15",
    name: "Echoes Library",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7748,
    lng: 106.7055,
    category: "Cafe",
    rating: 4.8,
    image: "https://picsum.photos/seed/library/800/600",
    images: ["https://picsum.photos/seed/library/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$",
    description: "A library cafe for calm conversations.",
    openingHours: "08:00 - 21:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Afternoon",
      target: "Quiet dates",
      outfit: "Cozy casual",
    },
    source: "mock",
  },
  {
    id: "16",
    name: "Vibrant Vinyl",
    address: "District 1, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7712,
    lng: 106.7088,
    category: "Entertainment",
    rating: 4.6,
    image: "https://picsum.photos/seed/vinyl/800/600",
    images: ["https://picsum.photos/seed/vinyl/800/600"],
    vibe: "Culture & Arts",
    priceRange: "$$",
    description: "A music-focused date spot with vinyl selections.",
    openingHours: "11:00 - 22:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Evening",
      target: "Music lovers",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "17",
    name: "Starlight Observatory",
    address: "District 7, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7685,
    lng: 106.7121,
    category: "Outdoor",
    rating: 4.9,
    image: "https://picsum.photos/seed/stars/800/600",
    images: ["https://picsum.photos/seed/stars/800/600"],
    vibe: "Quiet & Intimate",
    priceRange: "$$",
    description: "A dreamy nighttime date idea.",
    openingHours: "18:00 - 23:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Night",
      target: "Romantic dates",
      outfit: "Light jacket",
    },
    source: "mock",
  },
  {
    id: "18",
    name: "The Laugh Factory",
    address: "District 7, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7658,
    lng: 106.7154,
    category: "Entertainment",
    rating: 4.7,
    image: "https://picsum.photos/seed/comedy/800/600",
    images: ["https://picsum.photos/seed/comedy/800/600"],
    vibe: "Social & Loud",
    priceRange: "$$$",
    description: "A comedy-style entertainment date.",
    openingHours: "19:00 - 23:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Night",
      target: "Fun dates",
      outfit: "Casual",
    },
    source: "mock",
  },
  {
    id: "19",
    name: "Azure Poolside",
    address: "District 7, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7631,
    lng: 106.7187,
    category: "Outdoor",
    rating: 4.8,
    image: "https://picsum.photos/seed/pool/800/600",
    images: ["https://picsum.photos/seed/pool/800/600"],
    vibe: "Active & Outdoors",
    priceRange: "$$$",
    description: "A poolside hangout for relaxed sunny dates.",
    openingHours: "08:00 - 20:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Afternoon",
      target: "Relaxed dates",
      outfit: "Resort casual",
    },
    source: "mock",
  },
  {
    id: "20",
    name: "Midnight Munchies",
    address: "District 7, Ho Chi Minh City",
    city: "Ho Chi Minh City",
    lat: 10.7604,
    lng: 106.722,
    category: "Food",
    rating: 4.5,
    image: "https://picsum.photos/seed/street-food/800/600",
    images: ["https://picsum.photos/seed/street-food/800/600"],
    vibe: "Social & Loud",
    priceRange: "$",
    description: "A casual late-night food stop.",
    openingHours: "18:00 - 02:00",
    reviews: [],
    reviewSentiment: "Positive",
    recommendations: {
      bestTime: "Late night",
      target: "Casual dates",
      outfit: "Casual",
    },
    source: "mock",
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: "1",
    userId: "mock-user-1",
    userName: "Alex & Sam",
    userAvatar: "https://picsum.photos/seed/couple1/100/100",
    locationName: "The Velvet Nook",
    imageUrl: "https://picsum.photos/seed/post1/800/600",
    imageUrls: ["https://picsum.photos/seed/post1/800/600"],
    caption: "Best jazz night ever. The drinks were incredible!",
    rating: 5,
    timestamp: Date.now() - 1000 * 60 * 60 * 5,
    comments: [],
    reactions: [],
    savedBy: [],
    status: "already_went",
    dateType: "anniversary",
    priceLevel: "$$$",
    vibeTags: ["Quiet", "Jazz", "Romantic"],
    relationshipStage: "Long-term",
    bestForInsight: {
      bestTime: "Evening",
      seating: "Corner table",
      noiseLevel: "Low",
    },
  },
  {
    id: "2",
    userId: "mock-user-2",
    userName: "Jordan & Casey",
    userAvatar: "https://picsum.photos/seed/couple2/100/100",
    locationName: "Skyline Peaks",
    imageUrl: "https://picsum.photos/seed/post2/800/600",
    imageUrls: ["https://picsum.photos/seed/post2/800/600"],
    caption: "Woke up early for the sunrise. Totally worth it.",
    rating: 5,
    timestamp: Date.now() - 1000 * 60 * 60 * 24,
    comments: [],
    reactions: [],
    savedBy: [],
    status: "already_went",
    dateType: "chill",
    priceLevel: "$",
    vibeTags: ["Outdoor", "Sunrise", "Active"],
    relationshipStage: "Dating",
    bestForInsight: {
      bestTime: "Early morning",
      seating: "Open view",
      noiseLevel: "Low",
    },
  },
  {
    id: "3",
    userId: "mock-user-3",
    userName: "Taylor & Morgan",
    userAvatar: "https://picsum.photos/seed/couple3/100/100",
    locationName: "Canvas & Clay",
    imageUrl: "https://picsum.photos/seed/post3/800/600",
    imageUrls: ["https://picsum.photos/seed/post3/800/600"],
    caption: "Made some questionable pottery today. 10/10 experience.",
    rating: 5,
    timestamp: Date.now() - 1000 * 60 * 60 * 48,
    comments: [],
    reactions: [],
    savedBy: [],
    status: "already_went",
    dateType: "casual_hangout",
    priceLevel: "$$",
    vibeTags: ["Creative", "Art", "Funny"],
    relationshipStage: "New",
    bestForInsight: {
      bestTime: "Afternoon",
      seating: "Workshop table",
      noiseLevel: "Medium",
    },
  },
];

export const mockChatHistory: Message[] = [
  {
    id: "1",
    senderId: "user1",
    text: "Hey, what are we doing for our anniversary?",
    timestamp: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: "2",
    senderId: "user2",
    text: "I was thinking of that new jazz bar, The Velvet Nook?",
    timestamp: Date.now() - 1000 * 60 * 60 * 1.5,
  },
  {
    id: "3",
    senderId: "user1",
    text: "Ooh, sounds perfect! Let's book it.",
    timestamp: Date.now() - 1000 * 60 * 60,
  },
];